### ISSUE TITLE
Inquiry for seperate Spacenav Plugin

### ISSUE THREAD

**Issue by ruffsl** [ros-visualization/rviz_animated_view_controller#4]
Note quite an issue, but I'd like to inquire about the structure of a view_controller in the rviz library. 

My goal would be to have a node that subscribes to rosjoy message published by a spacenav_node and increment the camera's point and rotation accordingly to the input, thus both a ros node and an rviz frame_position_tracking_view_controller. I've seen some other project do quite similar things, i.e this [rviz_animated_view_controller](https://github.com/ros-visualization/rviz_animated_view_controller). I'm trying to make a subclass of say the [fps_view_controller](https://github.com/ros-visualization/rviz/blob/indigo-devel/src/rviz/default_plugin/view_controllers/fps_view_controller.h) that is also a node that subscribes to spacenav_node, but I can filter out the minimal relationship rviz_animated_view_controller has with rviz. I know how the node part can be launched and initialized, and subscribe, but I'm unsure how view_controller attaches or hooks into to a running instance of rviz,

pinging some old contributors:
@aleeper @otim @hershwg @dgossow
Here's hoping you find this well

**Comment by otim** [comment]
So you want to control the rviz camera with a spacenav joystick? What exactly do you want to control?

**Comment by ruffsl** [comment]
Hi @otim !

I posted a [similar question](http://answers.ros.org/question/218996/using-spacenav-to-control-rviz-view/) on answers.ros.org. In the question, I link to an example of how blender supports the use of the spacenav to adjust the 6DOF pose of the preview camera. I'd like to add the same functionality for the main rviz OpenGL view using a joy message from the spacenav node (but this could then support any mapping of a 6 axis controller I guess). That's my goal anyways.

**Comment by flynneva** [comment]
closing since its been ~6 years and doesnt look like anyones working on this?
